### ISSUE TITLE
An build error occured in the workflow of Build Package Version Listing

### ISSUE THREAD

**Issue by kesera2** [vrchat-community/template-package-listing#13]
Hello there.
An following build Error occured in Build Package Version Listing.
Does anyone know hot to fix this error?

> NUKE Execution Engine version 6.2.1 (Linux,.NETCoreApp,Version=v6.0)
​
BuildRepoListing
  Error: Could not download manifest from https://USERNAME.github.io/ThisNewRepoName/index.json
  11:04:04 [ERR] Could not download manifest from https://USERNAME.github.io/ThisNewRepoName/index.json

I'm wondering if source.json needs to rename to index.json.

**Comment by Spokeek** [comment]
I don't think so, this issue would more relate to a missconfiguration on the source.json source file. Can you verify this and maybe share where your configuration ?

**Comment by cstria0106** [comment]
You have to set GitHub Pages source to GitHub Action in the setting and re-run action with "Initial Commit" commit.
A chicken and egg situation...
